cloud:
  aws:
    credentials:
      access-key: AKIAWV5KTFUTTVKL2IFV
      secret-key: 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
    region: 
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: djv.box-desafionext


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
